export const MODULE_NAME = 'POPUP';
export const OPEN_MODAL = MODULE_NAME + '@@OPEN_MODAL';
export const CLOSE_MODAL = MODULE_NAME + '@@CLOSE_MODAL';
export const CHANGE_CONTENT_RENDER_MODAL =
  MODULE_NAME + '@@CHANGE_CONTENT_RENDER_MODAL';
export const CHANGE_MODAL_CONTENT = MODULE_NAME + '@@CHANGE_MODAL_CONTENT';
export const CHANGE_MODAL_STYLES = MODULE_NAME + '@@CHANGE_MODAL_STYLES';
export const ADD_CLASSES = MODULE_NAME + '@@ADD_CLASSES';
export const SHOW_LOADING_CONTENT = MODULE_NAME + '@@SHOW_LOADING_CONTENT';
